### ISSUE TITLE
create custom menu with additional <i></i> block

### ISSUE THREAD

**Issue by Cyberixxx** [joomlapro/plg_system_menuplus#5]
Hello
Your plug-in is able to create custom menus not only with Font Awesome, but such as  http://procssor.com/ - with custom pointers. it needs only to add custom image or span block, which are described on main css file. Can you do this, or i'll do this by myself?
![screen](https://f.cloud.github.com/assets/3163021/737574/e6878374-e331-11e2-877a-cd8acb6f8694.jpg)
i meen this ) this menu is made by your plug-in with my little modification

**Comment by brunowego** [comment]
This is a very nice feature to add in this plugin, you can contribute with this feature?

**Comment by Cyberixxx** [comment]
modified version is on branch, review it please

**Comment by Cyberixxx** [comment]
final version of this improvement is on branch, issue may be closed
