### ISSUE TITLE
Joomla 3.1.5 - plugin not working

### ISSUE THREAD

**Issue by Romskr** [joomlapro/plg_system_menuplus#7]
Hi!

Think, that plg_content_menuplus is very useful plugin to add icons for menu items, but very bad news for me - it's not working on Joomla 3.1.5
Don't know how to solve this problem.

Maybe there is other simple solution how to add bootstrap icons to the menu items?

Best regards.

**Comment by Cyberixxx** [comment]
Hi
The plugin is working fine, there troubles with font-awesome, i try to fix that
I found some conflicts with default template protostar, but with others works normally.
Can you explain what is your's template and how you have installed font-awesome?
